language: node_js
notifications:
  email: false
node_js:
  - '17'
cache:
  directories:
    - ~/.npm
    - .jest
script:
  - npm run test
after_success:
  - ./bin/codecov -e TRAVIS_NODE_VERSION -f coverage/*.json
  - ./bin/codecov -e TRAVIS_NODE_VERSION
dist: focal
sudo: false
